name: Notes Application CI Pipeline

on:
    push:
      branches:
        - main
        - develop
        - feature/*
    pull_request:
      branches:
        - main
        - develop
        - feature/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
        working-directory: ./src
      - name: Run linter
        run: npm run test-lint
        working-directory: ./src

  unit-tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Install dependencies
      run: npm clean-install
      working-directory: ./src
    - name: Run unit tests with coverage
      run: npm run test-unit
      working-directory: ./src
    - name: Upload test report
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: ./src/reports/report.xml
  
  deploy:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./coverage

