name: Notes Application CI Pipeline

on:
    push:
      branches:
        - '**'
    pull_request:
      branches:
        - '**'

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js 18.x
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "18"
  #     - name: Install dependencies
  #       run: npm install
  #       working-directory: ./src
  #     - name: Run linter
  #       run: npm run test-lint
  #       working-directory: ./src

  # unit-tests:
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Use Node.js 18.x
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: "18"
  #   - name: Install dependencies
  #     run: npm clean-install
  #     working-directory: ./src
  #   - name: Run unit tests with coverage
  #     run: npm run test-unit
  #     working-directory: ./src
  #   - name: Upload test report
  #     if: github.ref == 'refs/heads/main'
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: test-report
  #       path: ./src/reports/report.xml


  # deploy:
  #   needs: e2e-tests
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         personal_token: ${{ secrets.GH_PAT }}
  #         publish_dir: ./coverage

  e2e-tests:
  # needs: unit-tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: test
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    
    - name: Install dependencies
      run: npm install
      working-directory: ./src
    
    - name: Install Playwright Browsers
      run: npx playwright install
      working-directory: ./src

    # Install missing libraries
    - name: Install missing libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff1 \
          libvpx5 \
          libevent-2.1-7 \
          libopus0 \
          libgstreamer1.0-0 \
          libgstreamer-plugins-base1.0-0 \
          libharfbuzz0b \
          libhyphen0 \
          libflite1 \
          libgles2-mesa-dev \
          libx264-dev
    
    # Add this step to start your application
    - name: Start application
      run: npm start &
      working-directory: ./src
    
    # Add a delay to allow the application to start fully (optional, but recommended)
    - name: Wait for application to start
      run: sleep 10

    - name: Run e2e tests
      run: npx playwright test
      working-directory: ./src
    
    - name: Upload e2e test results
      uses: actions/upload-artifact@v3
      with:
        name: e2e-test-results
        path: ./src/test-results

